name = "NAOAssignments"
authors = ["Marco Riggirello", "Francesco Vaselli"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
DrWatson = "2.13.0"
julia = "1.9.4"
